#!/usr/bin/env python3
"""Sync architecture diagram SVGs to a Confluence page.

Phase 2 of the architecture documentation pipeline. Phase 1 renders
docs/architecture/workspace.dsl to SVG and commits the results back to main.
This script picks up those committed SVGs and pushes them to Confluence as page
attachments. The page body is edited ONCE (on first run) to add the embed
structure; on subsequent runs only the attachment data rotates.

Why REST and not the Atlassian MCP server: MCP is designed for interactive
agent use. CI does not need an agent layer over a documented REST API.

Why mix v1 and v2: the v2 API is the long-term direction but v1 is currently
better for attachment upload + storage-format body editing. Each call below
picks the API version that handles its operation cleanly. This is an
intentional, documented trade-off.

Body-edit-once contract: the first run inserts a sentinel HTML comment
(ARCHITECTURE_DIAGRAMS_AUTOGENERATED). Future runs see the sentinel and skip
body edits entirely, even if a human deletes the embed headings. To restore
the embed structure, manually re-trigger the workflow after removing the
sentinel from the page body.

Required environment variables:
    CONFLUENCE_API_TOKEN  - API token (secret)
    CONFLUENCE_USER_EMAIL - Atlassian account email tied to the token
    CONFLUENCE_BASE_URL   - e.g. https://morae.atlassian.net
    CONFLUENCE_PAGE_ID    - target page id (e.g. 218530029)

Optional:
    GITHUB_STEP_SUMMARY   - path to a markdown file appended for the run
                            summary in GitHub Actions. Ignored if unset.
"""

from __future__ import annotations

import base64
import os
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import requests

# The three rendered views we expect Phase 1 to have produced. Names match
# PlantUML's filename convention `structurizr-<ViewKey>.svg`. Renaming a view
# in workspace.dsl orphans its previous attachment until Confluence is cleaned
# up by hand — accepted trade-off.
EXPECTED_SVGS: tuple[str, ...] = (
    "structurizr-SystemContext.svg",
    "structurizr-Containers.svg",
    "structurizr-MatrixRun.svg",
)

SVG_DIR = Path("docs/architecture/exports/svg")

# Sentinel that marks the page body as managed by this script. Once present,
# the body is never re-edited. Stored as an HTML comment so it does not render
# in the published page.
SENTINEL = "ARCHITECTURE_DIAGRAMS_AUTOGENERATED"

# Storage-format snippet inserted on first run. Uses Confluence's `<ac:image>`
# + `<ri:attachment>` macros to embed the page-attached SVGs by filename. The
# sentinel comment is the contract anchor — do not remove from the template.
EMBED_BLOCK = (
    f"<!-- {SENTINEL} — body-edit-once contract; subsequent runs only "
    f"refresh attachments. -->"
    "<h2>Architecture diagrams</h2>"
    "<p>Source of truth: <code>docs/architecture/workspace.dsl</code> in the "
    "model-fitness repo. Diagrams below are auto-rendered and synced from CI.</p>"
    "<h3>System context</h3>"
    '<ac:image><ri:attachment ri:filename="structurizr-SystemContext.svg" /></ac:image>'
    "<h3>Containers</h3>"
    '<ac:image><ri:attachment ri:filename="structurizr-Containers.svg" /></ac:image>'
    "<h3>Matrix run (dynamic)</h3>"
    '<ac:image><ri:attachment ri:filename="structurizr-MatrixRun.svg" /></ac:image>'
)

# Heading we replace on first run. Two forms because the existing page may
# have been authored either via storage XML (heavier `<h2>...</h2>` tag) or
# via the editor's HTML output — both are functionally equivalent here.
HEADING_TARGETS: tuple[str, ...] = (
    "<h2>System context</h2>",
    "<h2>System Context</h2>",
)


@dataclass(frozen=True)
class Config:
    """Runtime configuration drawn from environment. Validated at construction."""

    base_url: str
    page_id: str
    user_email: str
    api_token: str

    @classmethod
    def from_env(cls) -> "Config":
        missing: list[str] = []
        # Order matches the workflow's check; keep them aligned so error
        # messages from script and workflow are easy to reconcile.
        env = {
            "CONFLUENCE_BASE_URL": os.environ.get("CONFLUENCE_BASE_URL", "").strip(),
            "CONFLUENCE_PAGE_ID": os.environ.get("CONFLUENCE_PAGE_ID", "").strip(),
            "CONFLUENCE_USER_EMAIL": os.environ.get("CONFLUENCE_USER_EMAIL", "").strip(),
            "CONFLUENCE_API_TOKEN": os.environ.get("CONFLUENCE_API_TOKEN", "").strip(),
        }
        for key, value in env.items():
            if not value:
                missing.append(key)
        if missing:
            raise SystemExit(
                "Missing or empty required environment variables: "
                + ", ".join(missing)
                + ". Set them as repo secrets/variables and re-run."
            )
        # Strip trailing slash so we can concatenate paths without doubling up.
        return cls(
            base_url=env["CONFLUENCE_BASE_URL"].rstrip("/"),
            page_id=env["CONFLUENCE_PAGE_ID"],
            user_email=env["CONFLUENCE_USER_EMAIL"],
            api_token=env["CONFLUENCE_API_TOKEN"],
        )

    def auth_header(self) -> str:
        """Confluence Cloud uses Basic auth with email:token."""
        raw = f"{self.user_email}:{self.api_token}".encode("utf-8")
        return "Basic " + base64.b64encode(raw).decode("ascii")


class ConfluenceClient:
    """Thin wrapper around requests for the small surface area we need.

    Retries once on transient 5xx with short exponential backoff. Auth errors
    (401/403) are not retried — they need human attention, not patience.
    """

    def __init__(self, cfg: Config) -> None:
        self.cfg = cfg
        self.session = requests.Session()
        # Default headers used on JSON requests. Multipart uploads override
        # Content-Type per call (and add the no-check CSRF header).
        self.session.headers.update(
            {
                "Authorization": cfg.auth_header(),
                "Accept": "application/json",
            }
        )

    def _request(
        self,
        method: str,
        url: str,
        *,
        retry_on_5xx: bool = True,
        **kwargs: Any,
    ) -> requests.Response:
        # One retry at 1.5s for transient 5xx. Anything more aggressive risks
        # hammering Confluence on a real outage.
        attempts = 0
        last_exc: Exception | None = None
        while attempts < 2:
            attempts += 1
            try:
                response = self.session.request(method, url, timeout=30, **kwargs)
            except requests.RequestException as exc:
                last_exc = exc
                if attempts >= 2:
                    raise
                time.sleep(1.5)
                continue
            if 500 <= response.status_code < 600 and retry_on_5xx and attempts < 2:
                time.sleep(1.5)
                continue
            return response
        # Unreachable: loop returns or raises before falling through.
        raise RuntimeError(f"Request failed: {last_exc}")

    @staticmethod
    def _raise_for_status(response: requests.Response, action: str) -> None:
        if response.ok:
            return
        body = response.text
        # Truncate verbose HTML error pages so the log stays useful.
        if len(body) > 800:
            body = body[:800] + "...[truncated]"
        if response.status_code in (401, 403):
            raise SystemExit(
                f"{action} failed with HTTP {response.status_code}. The API "
                "token may lack edit permission on the target page, or the "
                "email/token pair may be invalid. Body: " + body
            )
        if response.status_code == 409:
            raise SystemExit(
                f"{action} failed with HTTP 409 (version conflict). The page "
                "was edited between our metadata read and our update. The "
                "next sync will pick up the new version. Body: " + body
            )
        raise SystemExit(
            f"{action} failed with HTTP {response.status_code}. Body: {body}"
        )

    def get_page_v2(self) -> dict[str, Any]:
        """v2 page metadata is the cleanest source for current version number."""
        url = f"{self.cfg.base_url}/wiki/api/v2/pages/{self.cfg.page_id}"
        response = self._request("GET", url)
        self._raise_for_status(response, "Fetch page metadata (v2)")
        return response.json()

    def get_page_storage_v1(self) -> dict[str, Any]:
        """v1 page expand=body.storage is what we need to edit body in storage XML."""
        url = (
            f"{self.cfg.base_url}/wiki/rest/api/content/{self.cfg.page_id}"
            "?expand=body.storage,version"
        )
        response = self._request("GET", url)
        self._raise_for_status(response, "Fetch page body (v1)")
        return response.json()

    def list_attachments_v1(self) -> list[dict[str, Any]]:
        """v1 attachments listing is more mature than v2's equivalent today."""
        url = (
            f"{self.cfg.base_url}/wiki/rest/api/content/{self.cfg.page_id}"
            "/child/attachment?limit=200"
        )
        response = self._request("GET", url)
        self._raise_for_status(response, "List attachments (v1)")
        return response.json().get("results", [])

    def upload_attachment_create_v1(self, svg_path: Path) -> dict[str, Any]:
        url = (
            f"{self.cfg.base_url}/wiki/rest/api/content/{self.cfg.page_id}"
            "/child/attachment"
        )
        return self._post_attachment(url, svg_path, action="Create attachment")

    def upload_attachment_update_v1(
        self, attachment_id: str, svg_path: Path
    ) -> dict[str, Any]:
        url = (
            f"{self.cfg.base_url}/wiki/rest/api/content/{self.cfg.page_id}"
            f"/child/attachment/{attachment_id}/data"
        )
        return self._post_attachment(url, svg_path, action="Update attachment data")

    def _post_attachment(
        self, url: str, svg_path: Path, *, action: str
    ) -> dict[str, Any]:
        # X-Atlassian-Token: no-check is the documented CSRF bypass for
        # attachment uploads. Without it Confluence Cloud rejects the POST.
        # minorEdit=true suppresses watcher email notifications.
        headers = {
            "X-Atlassian-Token": "no-check",
            # Drop the session's default Accept; multipart endpoints do not
            # require it and some setups echo unexpected JSON-Accept errors.
        }
        with svg_path.open("rb") as fh:
            files = {
                "file": (svg_path.name, fh, "image/svg+xml"),
                "minorEdit": (None, "true"),
            }
            response = self._request(
                "POST", url, headers=headers, files=files, retry_on_5xx=True
            )
        self._raise_for_status(response, action)
        return response.json()

    def update_page_body_v1(
        self,
        *,
        title: str,
        new_storage_value: str,
        next_version: int,
    ) -> None:
        url = f"{self.cfg.base_url}/wiki/rest/api/content/{self.cfg.page_id}"
        payload = {
            "id": self.cfg.page_id,
            "type": "page",
            "title": title,
            "version": {"number": next_version},
            "body": {
                "storage": {
                    "value": new_storage_value,
                    "representation": "storage",
                }
            },
        }
        response = self._request(
            "PUT",
            url,
            headers={"Content-Type": "application/json"},
            json=payload,
        )
        self._raise_for_status(response, "Update page body (v1)")


def verify_svg_files() -> list[Path]:
    """Resolve and return the three expected SVG paths, or raise."""
    paths: list[Path] = []
    missing: list[str] = []
    for name in EXPECTED_SVGS:
        path = SVG_DIR / name
        if not path.is_file():
            missing.append(str(path))
        else:
            paths.append(path)
    if missing:
        raise SystemExit(
            "Expected rendered SVGs not found: "
            + ", ".join(missing)
            + ". Phase 1 (docs-architecture workflow) should produce these."
        )
    return paths


def insert_embed_block(body: str) -> tuple[str, bool]:
    """Insert the embed block in place of the System context heading.

    Returns (new_body, replaced_in_place). If the heading was found, the block
    replaces it. If not, the block is appended to the end of the body — log a
    warning at the call site so first-run robustness does not silently mutate
    a surprising layout.
    """
    for target in HEADING_TARGETS:
        if target in body:
            # Replace only the first occurrence; the heading is expected once.
            return body.replace(target, EMBED_BLOCK, 1), True
    return body + EMBED_BLOCK, False


def write_step_summary(lines: list[str]) -> None:
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary_path:
        return
    try:
        with open(summary_path, "a", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")
    except OSError as exc:
        # Don't fail the job over a summary write — just log.
        print(f"warning: could not write step summary: {exc}", file=sys.stderr)


def main() -> int:
    cfg = Config.from_env()
    svgs = verify_svg_files()
    client = ConfluenceClient(cfg)

    print(f"Fetching page metadata for id={cfg.page_id}")
    page_v2 = client.get_page_v2()
    title = page_v2.get("title", "Architecture")

    # v1 body fetch is needed regardless, both for the sentinel check and for
    # the page version (the v1 PUT requires it; v2 metadata's version is
    # equivalent here but v1's expand makes the body and version atomic).
    page_v1 = client.get_page_storage_v1()
    current_body = page_v1.get("body", {}).get("storage", {}).get("value", "") or ""
    current_version = int(page_v1.get("version", {}).get("number", 0))
    print(f"Page version (v1): {current_version}; body length: {len(current_body)}")

    # Build a lookup of existing attachment titles -> id, so we know whether
    # to create or update each SVG.
    existing = {a["title"]: a["id"] for a in client.list_attachments_v1()}
    print(f"Existing attachments on page: {len(existing)}")

    summary_attachment_lines: list[str] = []
    for svg_path in svgs:
        if svg_path.name in existing:
            attachment_id = existing[svg_path.name]
            print(f"Updating attachment data for {svg_path.name} (id={attachment_id})")
            client.upload_attachment_update_v1(attachment_id, svg_path)
            summary_attachment_lines.append(f"- updated `{svg_path.name}`")
        else:
            print(f"Creating attachment {svg_path.name}")
            client.upload_attachment_create_v1(svg_path)
            summary_attachment_lines.append(f"- created `{svg_path.name}`")

    # Body-edit-once contract: only edit if the sentinel is absent.
    body_action: str
    if SENTINEL in current_body:
        body_action = "skipped (sentinel present)"
        print("Sentinel present in body; skipping body edit per body-edit-once contract.")
    else:
        new_body, replaced_in_place = insert_embed_block(current_body)
        if not replaced_in_place:
            print(
                "warning: 'System context' heading not found in current body; "
                "appending embed block to end of body.",
                file=sys.stderr,
            )
        client.update_page_body_v1(
            title=title,
            new_storage_value=new_body,
            next_version=current_version + 1,
        )
        body_action = (
            "edited (replaced System context heading)"
            if replaced_in_place
            else "edited (appended; heading not found)"
        )
        print(f"Body updated to version {current_version + 1}.")

    page_url = f"{cfg.base_url}/wiki/spaces/MLI/pages/{cfg.page_id}"
    write_step_summary(
        [
            "## Confluence sync",
            f"- Page: [{title}]({page_url})",
            f"- Body: {body_action}",
            "- Attachments:",
            *[f"  {line[2:]}" for line in summary_attachment_lines],
        ]
    )
    print("Confluence sync complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
